resolver: lts-8.4

packages:
- '.'

extra-deps:
# more up-to-date than stack
- aeson-1.1.0.0
- serialize-instances-0.1.0.0
- storable-tuple-0.0.3.2
- vector-strategies-0.4
# my dependencies
- ADPfusion-0.5.2.2
- ADPfusionSet-0.0.0.1
- bimaps-0.1.0.2
- BiobaseXNA-0.9.3.1
- DPutils-0.0.1.0
- FormalGrammars-0.3.1.1
- OrderedBits-0.0.1.2
- PrimitiveArray-0.8.0.1
- PrimitiveArray-Pretty-0.0.0.2
- ShortestPathProblems-0.0.0.1
- ViennaRNA-bindings-0.233.1.2

flags:

